//+------------------------------------------------------------------+
//|                                                  TwoCandleEA.mq5 |
//|                                    Generated by Professional EA  |
//|                                                                  |
//+------------------------------------------------------------------+
#property copyright "Professional EA Developer"
#property version   "1.00"
#property description "EA based on two consecutive candles pattern"
#property description "with trailing stop and comprehensive logging"

//--- Include necessary libraries
#include <Trade/Trade.mqh>
#include <Trade/PositionInfo.mqh>
#include <Trade/SymbolInfo.mqh>

//--- Input parameters
// Timeframe selection
input ENUM_TIMEFRAMES InpTimeframe = PERIOD_CURRENT;     // Trading Timeframe

// Money Management
input double InpLotSize = 0.1;                           // Fixed Lot Size
input int InpStopLoss = 50;                               // Stop Loss (pips)
input int InpTakeProfit = 100;                            // Take Profit (pips)
input int InpTrailTrigger = 50;                           // Trail trigger (% of profit)
input int InpTrailDistance = 20;                          // Trailing Stop Distance (pips)

// Trade Settings
input int InpMagicNumber = 2024001;                       // EA Magic Number
input string InpTradeComment = "TwoCandle EA";            // Trade Comment

// Logging Settings
input bool InpEnableDebugLog = true;                       // Enable Debug Logging
input bool InpEnableFileLogging = true;                    // Enable File Logging

//--- Global variables
CTrade trade;
CPositionInfo positionInfo;
CSymbolInfo symbolInfo;
string logFileName;
bool isTradeOpen = false;
datetime lastBarTime = 0;
bool buySignal = false;
bool sellSignal = false;
datetime lastSLHitTime = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   // Initialize symbol info
   if(!symbolInfo.Name(Symbol()))
   {
      Print("Failed to initialize symbol info");
      return INIT_FAILED;
   }
   symbolInfo.RefreshRates();
   
   // Initialize trade object
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(10);
   trade.SetTypeFillingBySymbol(Symbol());
   trade.SetAsyncMode(false);
   
   // Create log file
   if(InpEnableFileLogging)
   {
      logFileName = "TwoCandleEA_" + Symbol() + "_" + IntegerToString(TimeCurrent()) + ".log";
      WriteToLog("========== EA Started ==========");
      WriteToLog("Symbol: " + Symbol());
      WriteToLog("Timeframe: " + EnumToString(InpTimeframe));
      WriteToLog("Magic Number: " + IntegerToString(InpMagicNumber));
      WriteToLog("Lot Size: " + DoubleToString(InpLotSize, 2));
      WriteToLog("Stop Loss: " + IntegerToString(InpStopLoss) + " pips");
      WriteToLog("Take Profit: " + IntegerToString(InpTakeProfit) + " pips");
      WriteToLog("Trail Trigger: " + IntegerToString(InpTrailTrigger) + "%");
      WriteToLog("Trail Distance: " + IntegerToString(InpTrailDistance) + " pips");
      WriteToLog("=================================");
   }
   
   DebugLog("EA initialized successfully");
   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   DebugLog("EA deinitialized. Reason: " + IntegerToString(reason));
   if(InpEnableFileLogging)
   {
      WriteToLog("========== EA Stopped ==========");
   }
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   // Check for new bar
   if(!IsNewBar())
      return;
   
   DebugLog("New bar detected. Time: " + TimeToString(TimeCurrent()));
   
   // Check if there's an open position
   isTradeOpen = CheckOpenPositions();
   
   if(isTradeOpen)
   {
      // Manage trailing stop for open position
      ManageTrailingStop();
   }
   else
   {
      // Check if SL was hit recently (skip trading for current bar if SL was hit)
      datetime currentBarTime = iTime(Symbol(), InpTimeframe, 0);
      if(lastSLHitTime == currentBarTime)
      {
         DebugLog("SL was hit this bar - skipping new trades");
         return;
      }
      
      // Check for entry signals
      CheckEntrySignals();
      
      // Execute trades based on signals
      if(buySignal)
      {
         DebugLog("BUY signal detected - attempting to open trade");
         OpenBuyTrade();
         buySignal = false; // Reset signal
      }
      else if(sellSignal)
      {
         DebugLog("SELL signal detected - attempting to open trade");
         OpenSellTrade();
         sellSignal = false; // Reset signal
      }
   }
}

//+------------------------------------------------------------------+
//| Check if it's a new bar                                          |
//+------------------------------------------------------------------+
bool IsNewBar()
{
   datetime currentBarTime = iTime(Symbol(), InpTimeframe, 0);
   if(currentBarTime != lastBarTime)
   {
      lastBarTime = currentBarTime;
      return true;
   }
   return false;
}

//+------------------------------------------------------------------+
//| Check for entry signals                                          |
//+------------------------------------------------------------------+
void CheckEntrySignals()
{
   // Get the last 3 candles (we need 2 candles for signal + current candle)
   MqlRates candles[];
   ArraySetAsSeries(candles, true);
   
   int copied = CopyRates(Symbol(), InpTimeframe, 1, 3, candles);
   if(copied < 3)
   {
      DebugLog("Failed to copy candle data. Error: " + IntegerToString(GetLastError()));
      return;
   }
   
   // Check for two consecutive bullish candles
   bool twoBullishCandles = (candles[0].close > candles[0].open) && 
                            (candles[1].close > candles[1].open);
   
   // Check for two consecutive bearish candles
   bool twoBearishCandles = (candles[0].close < candles[0].open) && 
                            (candles[1].close < candles[1].open);
   
   // Set signals based on candle pattern
   if(twoBullishCandles)
   {
      DebugLog("Two bullish candles detected. Candle 1: Open=" + DoubleToString(candles[1].open, Digits()) + 
               " Close=" + DoubleToString(candles[1].close, Digits()) + 
               " Candle 2: Open=" + DoubleToString(candles[0].open, Digits()) + 
               " Close=" + DoubleToString(candles[0].close, Digits()));
      buySignal = true;
      sellSignal = false;
   }
   else if(twoBearishCandles)
   {
      DebugLog("Two bearish candles detected. Candle 1: Open=" + DoubleToString(candles[1].open, Digits()) + 
               " Close=" + DoubleToString(candles[1].close, Digits()) + 
               " Candle 2: Open=" + DoubleToString(candles[0].open, Digits()) + 
               " Close=" + DoubleToString(candles[0].close, Digits()));
      sellSignal = true;
      buySignal = false;
   }
   else
   {
      DebugLog("No valid candle pattern detected");
      buySignal = false;
      sellSignal = false;
   }
}

//+------------------------------------------------------------------+
//| Open Buy Trade                                                   |
//+------------------------------------------------------------------+
void OpenBuyTrade()
{
   symbolInfo.RefreshRates();
   
   double price = symbolInfo.Ask();
   double sl = 0;
   double tp = 0;
   
   // Calculate pip value
   double pipValue = SymbolInfoDouble(Symbol(), SYMBOL_TRADE_TICK_SIZE) * 10;
   double pipPoint = SymbolInfoDouble(Symbol(), SYMBOL_POINT);
   double slPoints = InpStopLoss * 10 * pipPoint * 10; // Convert pips to price
   double tpPoints = InpTakeProfit * 10 * pipPoint * 10;
   
   if(InpStopLoss > 0)
      sl = price - slPoints;
   
   if(InpTakeProfit > 0)
      tp = price + tpPoints;
   
   DebugLog("Attempting BUY order - Price: " + DoubleToString(price, Digits()) + 
            " SL: " + DoubleToString(sl, Digits()) + 
            " TP: " + DoubleToString(tp, Digits()));
   
   // Send order
   if(trade.Buy(InpLotSize, Symbol(), price, sl, tp, InpTradeComment))
   {
      if(trade.ResultRetcode() == TRADE_RETCODE_DONE)
      {
         DebugLog("BUY order executed successfully. Ticket: " + IntegerToString(trade.ResultOrder()));
         DebugLog("Entry price: " + DoubleToString(trade.ResultPrice(), Digits()));
         string logMsg = StringFormat("BUY OPEN - Ticket: %d, Price: %f, SL: %f, TP: %f", 
                        trade.ResultOrder(), trade.ResultPrice(), sl, tp);
         WriteToLog(logMsg);
      }
      else
      {
         DebugLog("BUY order failed. Return code: " + IntegerToString(trade.ResultRetcode()) + 
                  " - " + trade.ResultRetcodeDescription());
      }
   }
   else
   {
      DebugLog("BUY order placement failed. Error: " + IntegerToString(GetLastError()));
   }
}

//+------------------------------------------------------------------+
//| Open Sell Trade                                                  |
//+------------------------------------------------------------------+
void OpenSellTrade()
{
   symbolInfo.RefreshRates();
   
   double price = symbolInfo.Bid();
   double sl = 0;
   double tp = 0;
   
   // Calculate pip value
   double pipValue = SymbolInfoDouble(Symbol(), SYMBOL_TRADE_TICK_SIZE) * 10;
   double pipPoint = SymbolInfoDouble(Symbol(), SYMBOL_POINT);
   double slPoints = InpStopLoss * 10 * pipPoint * 10; // Convert pips to price
   double tpPoints = InpTakeProfit * 10 * pipPoint * 10;
   
   if(InpStopLoss > 0)
      sl = price + slPoints;
   
   if(InpTakeProfit > 0)
      tp = price - tpPoints;
   
   DebugLog("Attempting SELL order - Price: " + DoubleToString(price, Digits()) + 
            " SL: " + DoubleToString(sl, Digits()) + 
            " TP: " + DoubleToString(tp, Digits()));
   
   // Send order
   if(trade.Sell(InpLotSize, Symbol(), price, sl, tp, InpTradeComment))
   {
      if(trade.ResultRetcode() == TRADE_RETCODE_DONE)
      {
         DebugLog("SELL order executed successfully. Ticket: " + IntegerToString(trade.ResultOrder()));
         DebugLog("Entry price: " + DoubleToString(trade.ResultPrice(), Digits()));
         string logMsg = StringFormat("SELL OPEN - Ticket: %d, Price: %f, SL: %f, TP: %f", 
                        trade.ResultOrder(), trade.ResultPrice(), sl, tp);
         WriteToLog(logMsg);
      }
      else
      {
         DebugLog("SELL order failed. Return code: " + IntegerToString(trade.ResultRetcode()) + 
                  " - " + trade.ResultRetcodeDescription());
      }
   }
   else
   {
      DebugLog("SELL order placement failed. Error: " + IntegerToString(GetLastError()));
   }
}

//+------------------------------------------------------------------+
//| Check for open positions                                         |
//+------------------------------------------------------------------+
bool CheckOpenPositions()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(positionInfo.SelectByIndex(i))
      {
         if(positionInfo.Symbol() == Symbol() && positionInfo.Magic() == InpMagicNumber)
         {
            DebugLog("Open position found - Ticket: " + IntegerToString(positionInfo.Ticket()) + 
                     " Type: " + EnumToString(positionInfo.PositionType()) + 
                     " Price: " + DoubleToString(positionInfo.PriceOpen(), Digits()) +
                     " Profit: " + DoubleToString(positionInfo.Profit(), 2));
            return true;
         }
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Manage trailing stop                                             |
//+------------------------------------------------------------------+
void ManageTrailingStop()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(positionInfo.SelectByIndex(i))
      {
         if(positionInfo.Symbol() == Symbol() && positionInfo.Magic() == InpMagicNumber)
         {
            double currentSL = positionInfo.StopLoss();
            double currentTP = positionInfo.TakeProfit();
            double openPrice = positionInfo.PriceOpen();
            double currentPrice;
            double breakevenPrice;
            
            // Calculate pip value and point
            double pipValue = SymbolInfoDouble(Symbol(), SYMBOL_TRADE_TICK_SIZE) * 10;
            double pipPoint = SymbolInfoDouble(Symbol(), SYMBOL_POINT);
            double trailDistancePoints = InpTrailDistance * 10 * pipPoint * 10;
            double slPoints = InpStopLoss * 10 * pipPoint * 10;
            
            // Calculate current profit percentage
            double profitPoints, profitPercent;
            
            if(positionInfo.PositionType() == POSITION_TYPE_BUY)
            {
               currentPrice = symbolInfo.Bid();
               profitPoints = (currentPrice - openPrice) / (pipPoint * 10); // Convert to pips
               profitPercent = (profitPoints / InpTakeProfit) * 100;
               
               // Check if position is still open and we need to trail
               if(profitPercent >= InpTrailTrigger)
               {
                  // Calculate new trailing stop
                  // New SL = Current Price - Trail Distance
                  double newSL = currentPrice - trailDistancePoints;
                  
                  // Ensure we don't move SL below breakeven or backwards
                  double minSL = openPrice + (pipPoint * 10); // Breakeven + 1 pip
                  
                  if(newSL < minSL)
                     newSL = minSL;
                  
                  // Only modify if new SL is higher than current SL
                  if(newSL > currentSL)
                  {
                     DebugLog(StringFormat("BUY Trail - Price: %f, Profit: %.1f pips (%.1f%%), Current SL: %f, New SL: %f", 
                              currentPrice, profitPoints, profitPercent, currentSL, newSL));
                     
                     if(trade.PositionModify(positionInfo.Ticket(), newSL, currentTP))
                     {
                        DebugLog("Trailing stop modified successfully for BUY position");
                        string logMsg = StringFormat("TRAIL STOP BUY - Ticket: %d, New SL: %f, Profit: %.1f pips", 
                                       positionInfo.Ticket(), newSL, profitPoints);
                        WriteToLog(logMsg);
                     }
                     else
                     {
                        DebugLog("Failed to modify trailing stop. Error: " + IntegerToString(GetLastError()));
                     }
                  }
               }
               else
               {
                  DebugLog(StringFormat("BUY Position - Profit: %.1f pips (%.1f%%) - Waiting for trail trigger (%.0f%%)", 
                           profitPoints, profitPercent, InpTrailTrigger));
               }
               
               // Check if SL was hit
               if(currentSL != 0 && currentPrice <= currentSL)
               {
                  DebugLog("Stop Loss hit for BUY position: " + IntegerToString(positionInfo.Ticket()));
                  lastSLHitTime = iTime(Symbol(), InpTimeframe, 0);
                  string logMsg = StringFormat("SL HIT BUY - Ticket: %d, Price: %f, SL: %f", 
                                 positionInfo.Ticket(), currentPrice, currentSL);
                  WriteToLog(logMsg);
               }
            }
            else if(positionInfo.PositionType() == POSITION_TYPE_SELL)
            {
               currentPrice = symbolInfo.Ask();
               profitPoints = (openPrice - currentPrice) / (pipPoint * 10); // Convert to pips
               profitPercent = (profitPoints / InpTakeProfit) * 100;
               
               // Check if position is still open and we need to trail
               if(profitPercent >= InpTrailTrigger)
               {
                  // Calculate new trailing stop
                  // New SL = Current Price + Trail Distance
                  double newSL = currentPrice + trailDistancePoints;
                  
                  // Ensure we don't move SL below breakeven or backwards
                  double maxSL = openPrice - (pipPoint * 10); // Breakeven - 1 pip
                  
                  if(newSL > maxSL)
                     newSL = maxSL;
                  
                  // Only modify if new SL is lower than current SL (for sell positions)
                  if(newSL < currentSL || currentSL == 0)
                  {
                     DebugLog(StringFormat("SELL Trail - Price: %f, Profit: %.1f pips (%.1f%%), Current SL: %f, New SL: %f", 
                              currentPrice, profitPoints, profitPercent, currentSL, newSL));
                     
                     if(trade.PositionModify(positionInfo.Ticket(), newSL, currentTP))
                     {
                        DebugLog("Trailing stop modified successfully for SELL position");
                        string logMsg = StringFormat("TRAIL STOP SELL - Ticket: %d, New SL: %f, Profit: %.1f pips", 
                                       positionInfo.Ticket(), newSL, profitPoints);
                        WriteToLog(logMsg);
                     }
                     else
                     {
                        DebugLog("Failed to modify trailing stop. Error: " + IntegerToString(GetLastError()));
                     }
                  }
               }
               else
               {
                  DebugLog(StringFormat("SELL Position - Profit: %.1f pips (%.1f%%) - Waiting for trail trigger (%.0f%%)", 
                           profitPoints, profitPercent, InpTrailTrigger));
               }
               
               // Check if SL was hit
               if(currentSL != 0 && currentPrice >= currentSL)
               {
                  DebugLog("Stop Loss hit for SELL position: " + IntegerToString(positionInfo.Ticket()));
                  lastSLHitTime = iTime(Symbol(), InpTimeframe, 0);
                  string logMsg = StringFormat("SL HIT SELL - Ticket: %d, Price: %f, SL: %f", 
                                 positionInfo.Ticket(), currentPrice, currentSL);
                  WriteToLog(logMsg);
               }
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Debug logging function                                           |
//+------------------------------------------------------------------+
void DebugLog(string message)
{
   if(InpEnableDebugLog)
   {
      Print(TimeToString(TimeCurrent(), TIME_DATE|TIME_SECONDS) + " - " + message);
   }
   
   if(InpEnableFileLogging)
   {
      WriteToLog(message);
   }
}

//+------------------------------------------------------------------+
//| Write to log file                                                |
//+------------------------------------------------------------------+
void WriteToLog(string message)
{
   if(!InpEnableFileLogging)
      return;
      
   int handle = FileOpen(logFileName, FILE_WRITE|FILE_READ|FILE_TXT, "\t");
   if(handle != INVALID_HANDLE)
   {
      FileSeek(handle, 0, SEEK_END);
      FileWrite(handle, TimeToString(TimeCurrent(), TIME_DATE|TIME_SECONDS) + " - " + message);
      FileClose(handle);
   }
}

//+------------------------------------------------------------------+
//| Expert tick function (for handling trade events)                 |
//+------------------------------------------------------------------+
void OnTrade()
{
   DebugLog("Trade event detected");
}

//+------------------------------------------------------------------+
//| Expert trade transaction function                                |
//+------------------------------------------------------------------+
void OnTradeTransaction(const MqlTradeTransaction& trans,
                        const MqlTradeRequest& request,
                        const MqlTradeResult& result)
{
   if(trans.type == TRADE_TRANSACTION_DEAL_ADD)
   {
      DebugLog("Transaction: Deal added - Ticket: " + IntegerToString(trans.deal));
   }
}
//+------------------------------------------------------------------+