//+------------------------------------------------------------------+
//|                                          TrendPullbackEA.mq5     |
//|                                        Generated by AI Assistant |
//|                                                                  |
//| This EA implements a trend-following strategy.                  |
//| It identifies the overarching trend on a Daily timeframe and     |
//| looks for pullback entries on a 4-hour or 1-hour chart.         |
//| Features 1% account risk per trade, fixed risk-reward ratios,    |
//| and a trailing stop.                                             |
//+------------------------------------------------------------------+
#property copyright "AI Assistant"
#property link      ""
#property version   "1.00"

// --- Include Trade Library ---
#include <Trade/Trade.mqh>
CTrade trade;

//+------------------------------------------------------------------+
//| Input Parameters                                                 |
//+------------------------------------------------------------------+

// --- Trend Identification (Higher Timeframe) ---
input group "=== Trend Identification (Higher Timeframe) ==="
input ENUM_TIMEFRAMES   TrendTimeframe         = PERIOD_D1; // Trend Timeframe (e.g., D1)
input int               TrendMAPeriod          = 200;        // Trend MA Period
input ENUM_MA_METHOD    TrendMAMethod          = MODE_SMA;   // Trend MA Method
input ENUM_APPLIED_PRICE TrendMAAppliedPrice   = PRICE_CLOSE;// Trend MA Applied Price

// --- Entry Settings (Lower Timeframe) ---
input group "=== Entry Settings (Lower Timeframe) ==="
input ENUM_TIMEFRAMES   EntryTimeframe         = PERIOD_H4; // Entry Timeframe (e.g., H4 or H1)
input int               EntryMAPeriod          = 50;         // Entry MA Period (for confirmation)
input ENUM_MA_METHOD    EntryMAMethod          = MODE_SMA;   // Entry MA Method
input ENUM_APPLIED_PRICE EntryMAAppliedPrice   = PRICE_CLOSE;// Entry MA Applied Price
input int               LookbackSwing          = 10;         // Lookback candles for swing high/low

// --- Risk Management ---
input group "=== Risk Management ==="
input double            RiskPercent            = 1.0;        // Risk % of account per trade
input double            RiskRewardRatio        = 2.0;        // Risk:Reward Ratio (e.g., 2 for 1:2)
input bool              UseTrailingStop        = true;       // Enable/Disable Trailing Stop
input double            TrailingStopPips       = 30.0;       // Trailing stop distance in pips
input double            TrailingStepPips       = 10.0;       // Trailing step in pips

// --- Trade Settings ---
input group "=== Trade Settings ==="
input int               MagicNumber            = 98765;      // Unique EA Magic Number
input string            TradeComment           = "TrendPullback"; // Trade Comment
input int               Slippage               = 10;         // Slippage in points

// --- Global Variables ---
double dTrendMA[];
double dEntryMA[];
double dHigh[];
double dLow[];
double pipValue;
double point;
double tickSize;

//+------------------------------------------------------------------+
//| Expert Initialization Function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
// Initialize trade object
   trade.SetExpertMagicNumber(MagicNumber);
   trade.SetDeviationInPoints(Slippage);
   trade.SetAsyncMode(false);

// Get symbol properties
   point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   pipValue = point * 10; // For 5-digit brokers, 10 points = 1 pip. For 4-digit, point = pip.

// Set up indicator buffers
   ArraySetAsSeries(dTrendMA, true);
   ArraySetAsSeries(dEntryMA, true);
   ArraySetAsSeries(dHigh, true);
   ArraySetAsSeries(dLow, true);

   Print("EA initialized successfully. Point: ", point, " Pip Value: ", pipValue);
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert Deinitialization Function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   Print("EA deinitialized. Reason: ", reason);
}


//+------------------------------------------------------------------+
//| Check if a position already exists for this symbol              |
//+------------------------------------------------------------------+
bool PositionExists()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      string positionSymbol = PositionGetSymbol(i);
      if(positionSymbol == _Symbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber)
         return true;
     }
   return false;
}

//+------------------------------------------------------------------+
//| Get Trend Direction from Higher Timeframe                       |
//+------------------------------------------------------------------+
int GetTrendDirection()
{
// Get Trend MA values
   int maHandle = iMA(_Symbol, TrendTimeframe, TrendMAPeriod, 0, TrendMAMethod, TrendMAAppliedPrice);
   if(maHandle == INVALID_HANDLE)
     {
      Print("Failed to create Trend MA handle");
      return 0;
     }

// Copy MA values
   if(CopyBuffer(maHandle, 0, 1, 1, dTrendMA) < 1)
     {
      Print("Failed to copy Trend MA buffer");
      IndicatorRelease(maHandle);
      return 0;
     }

   IndicatorRelease(maHandle);

// Get current price on higher timeframe
   double trendClose[];
   ArraySetAsSeries(trendClose, true);
   if(CopyClose(_Symbol, TrendTimeframe, 0, 2, trendClose) < 2)
     {
      Print("Failed to copy trend timeframe close prices");
      return 0;
     }

// Determine trend
   double currentPrice = trendClose[0];
   double trendMA = dTrendMA[0];

// Uptrend: price above MA
   if(currentPrice > trendMA)
      return 1;
// Downtrend: price below MA
   else if(currentPrice < trendMA)
      return -1;
   else
      return 0;
}

//+------------------------------------------------------------------+
//| Check Buy Entry Conditions (Pullback in Uptrend)                |
//+------------------------------------------------------------------+
bool CheckBuyEntry()
{
// Get Entry MA values
   int maHandle = iMA(_Symbol, EntryTimeframe, EntryMAPeriod, 0, EntryMAMethod, EntryMAAppliedPrice);
   if(maHandle == INVALID_HANDLE)
     {
      Print("Failed to create Entry MA handle");
      return false;
     }

   if(CopyBuffer(maHandle, 0, 0, 2, dEntryMA) < 2)
     {
      Print("Failed to copy Entry MA buffer");
      IndicatorRelease(maHandle);
      return false;
     }
   IndicatorRelease(maHandle);

// Get swing low (pullback level)
   if(CopyLow(_Symbol, EntryTimeframe, 1, LookbackSwing, dLow) < LookbackSwing)
     {
      Print("Failed to copy low prices for swing detection");
      return false;
     }

   double swingLow = dLow[ArrayMinimum(dLow)];

// Get current price
   double currentPrice[];
   ArraySetAsSeries(currentPrice, true);
   if(CopyClose(_Symbol, EntryTimeframe, 0, 1, currentPrice) < 1)
     {
      Print("Failed to copy current price");
      return false;
     }

// Conditions for Buy Entry:
// 1. Price is above the Entry MA (overall trend on entry timeframe)
// 2. Price has pulled back to near the swing low
// 3. Current price is at or near the swing low (pullback)

   if(currentPrice[0] > dEntryMA[0] && currentPrice[0] <= swingLow * 1.001) // Allowing 0.1% proximity
     {
      return true;
     }

   return false;
}

//+------------------------------------------------------------------+
//| Check Sell Entry Conditions (Pullback in Downtrend)             |
//+------------------------------------------------------------------+
bool CheckSellEntry()
{
// Get Entry MA values
   int maHandle = iMA(_Symbol, EntryTimeframe, EntryMAPeriod, 0, EntryMAMethod, EntryMAAppliedPrice);
   if(maHandle == INVALID_HANDLE)
     {
      Print("Failed to create Entry MA handle");
      return false;
     }

   if(CopyBuffer(maHandle, 0, 0, 2, dEntryMA) < 2)
     {
      Print("Failed to copy Entry MA buffer");
      IndicatorRelease(maHandle);
      return false;
     }
   IndicatorRelease(maHandle);

// Get swing high (pullback level)
   if(CopyHigh(_Symbol, EntryTimeframe, 1, LookbackSwing, dHigh) < LookbackSwing)
     {
      Print("Failed to copy high prices for swing detection");
      return false;
     }

   double swingHigh = dHigh[ArrayMaximum(dHigh)];

// Get current price
   double currentPrice[];
   ArraySetAsSeries(currentPrice, true);
   if(CopyClose(_Symbol, EntryTimeframe, 0, 1, currentPrice) < 1)
     {
      Print("Failed to copy current price");
      return false;
     }

// Conditions for Sell Entry:
// 1. Price is below the Entry MA (overall trend on entry timeframe)
// 2. Price has pulled back to near the swing high
// 3. Current price is at or near the swing high (pullback)

   if(currentPrice[0] < dEntryMA[0] && currentPrice[0] >= swingHigh * 0.999) // Allowing 0.1% proximity
     {
      return true;
     }

   return false;
}

//+------------------------------------------------------------------+
//| Execute Buy Order                                               |
//+------------------------------------------------------------------+
void ExecuteBuy()
{
// Get swing low for stop loss
   if(CopyLow(_Symbol, EntryTimeframe, 1, LookbackSwing, dLow) < LookbackSwing)
     {
      Print("Failed to copy low prices for SL calculation");
      return;
     }
   double swingLow = dLow[ArrayMinimum(dLow)];

// Get current price
   double currentPrice[];
   ArraySetAsSeries(currentPrice, true);
   if(CopyClose(_Symbol, EntryTimeframe, 0, 1, currentPrice) < 1)
     {
      Print("Failed to copy current price for entry");
      return;
     }
   double entryPrice = currentPrice[0];

// Calculate stop loss price (just below swing low)
   double slPrice = swingLow - (2 * point); // 2 points below swing low for safety

// Calculate risk in price terms
   double riskPoints = (entryPrice - slPrice) / point;
   double riskPips = riskPoints / 10; // For 5-digit brokers

// Calculate take profit based on risk:reward ratio
   double tpPrice = entryPrice + (riskPoints * RiskRewardRatio * point);

// Calculate lot size based on 1% risk
   double lotSize = CalculateLotSize(entryPrice, slPrice, RiskPercent);

   if(lotSize <= 0)
     {
      Print("Invalid lot size calculated: ", lotSize);
      return;
     }

   Print("Buy Signal - Entry: ", entryPrice, " SL: ", slPrice, " TP: ", tpPrice, " Lot: ", lotSize, " Risk Pips: ", riskPips);

// Send order
   trade.Buy(lotSize, _Symbol, entryPrice, slPrice, tpPrice, TradeComment);

// Check result
   if(trade.ResultRetcode() == TRADE_RETCODE_DONE)
     {
      Print("Buy order placed successfully. Ticket: ", trade.ResultOrder());
      if(UseTrailingStop)
         Print("Trailing stop enabled for this position.");
     }
   else
     {
      Print("Buy order failed. Retcode: ", trade.ResultRetcode(), " ", trade.ResultRetcodeDescription());
     }
}

//+------------------------------------------------------------------+
//| Execute Sell Order                                              |
//+------------------------------------------------------------------+
void ExecuteSell()
{
// Get swing high for stop loss
   if(CopyHigh(_Symbol, EntryTimeframe, 1, LookbackSwing, dHigh) < LookbackSwing)
     {
      Print("Failed to copy high prices for SL calculation");
      return;
     }
   double swingHigh = dHigh[ArrayMaximum(dHigh)];

// Get current price
   double currentPrice[];
   ArraySetAsSeries(currentPrice, true);
   if(CopyClose(_Symbol, EntryTimeframe, 0, 1, currentPrice) < 1)
     {
      Print("Failed to copy current price for entry");
      return;
     }
   double entryPrice = currentPrice[0];

// Calculate stop loss price (just above swing high)
   double slPrice = swingHigh + (2 * point); // 2 points above swing high for safety

// Calculate risk in price terms
   double riskPoints = (slPrice - entryPrice) / point;
   double riskPips = riskPoints / 10; // For 5-digit brokers

// Calculate take profit based on risk:reward ratio
   double tpPrice = entryPrice - (riskPoints * RiskRewardRatio * point);

// Calculate lot size based on 1% risk
   double lotSize = CalculateLotSize(entryPrice, slPrice, RiskPercent);

   if(lotSize <= 0)
     {
      Print("Invalid lot size calculated: ", lotSize);
      return;
     }

   Print("Sell Signal - Entry: ", entryPrice, " SL: ", slPrice, " TP: ", tpPrice, " Lot: ", lotSize, " Risk Pips: ", riskPips);

// Send order
   trade.Sell(lotSize, _Symbol, entryPrice, slPrice, tpPrice, TradeComment);

// Check result
   if(trade.ResultRetcode() == TRADE_RETCODE_DONE)
     {
      Print("Sell order placed successfully. Ticket: ", trade.ResultOrder());
      if(UseTrailingStop)
         Print("Trailing stop enabled for this position.");
     }
   else
     {
      Print("Sell order failed. Retcode: ", trade.ResultRetcode(), " ", trade.ResultRetcodeDescription());
     }
}

//+------------------------------------------------------------------+
//| Calculate Lot Size based on Risk %                              |
//+------------------------------------------------------------------+
double CalculateLotSize(double entryPrice, double stopLossPrice, double riskPercent)
{
// Get account balance
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = balance * (riskPercent / 100.0);

// Calculate risk in points
   double riskPoints = MathAbs(entryPrice - stopLossPrice) / point;
   if(riskPoints == 0)
     {
      Print("Risk points is zero. Invalid SL distance.");
      return 0;
     }

// Get tick value and tick size for accurate lot calculation
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   if(tickValue == 0)
     {
      Print("Tick value is zero. Cannot calculate lot size.");
      return 0;
     }

// Value per point = tick value * (1 point / tick size)
   double valuePerPoint = tickValue * (point / tickSize);

// Calculate raw lot size
   double rawLotSize = riskAmount / (riskPoints * valuePerPoint);

// Normalize lot size to broker's limits
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);

   double normalizedLotSize = MathFloor(rawLotSize / lotStep) * lotStep;
   normalizedLotSize = MathMax(minLot, MathMin(maxLot, normalizedLotSize));

   return normalizedLotSize;
}

//+------------------------------------------------------------------+
//| Expert Tick Function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   // Check for new bar on the entry timeframe to avoid multiple signals per bar
   static datetime lastBarTime = 0;
   datetime currentBarTime = iTime(_Symbol, EntryTimeframe, 0);
   
   // If this is a new bar, process entry signals
   if(currentBarTime != lastBarTime)
   {
      lastBarTime = currentBarTime;
      
      // --- 1. Check if a position is already open ---
      if(!PositionExists())
      {
         // --- 2. Get trend direction from higher timeframe ---
         int trendDirection = GetTrendDirection();
         
         if(trendDirection > 0) // Uptrend
         {
            if(CheckBuyEntry())
               ExecuteBuy();
         }
         else if(trendDirection < 0) // Downtrend
         {
            if(CheckSellEntry())
               ExecuteSell();
         }
      }
   }
   
   // --- 3. Always manage trailing stop for open positions (every tick) ---
   if(UseTrailingStop)
   {
      ManageTrailingStop();
   }
}

//+------------------------------------------------------------------+
//| Manage Trailing Stop for Open Positions                         |
//+------------------------------------------------------------------+
void ManageTrailingStop()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      if(PositionSelectByTicket(PositionGetTicket(i)))
        {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber)
           {
            double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
            double currentStopLoss = PositionGetDouble(POSITION_SL);
            double currentPrice = (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) ? SymbolInfoDouble(_Symbol, SYMBOL_BID) : SymbolInfoDouble(_Symbol, SYMBOL_ASK);
            double newStopLoss = currentStopLoss;

            int positionType = (int)PositionGetInteger(POSITION_TYPE);

            if(positionType == POSITION_TYPE_BUY)
              {
               // Calculate new trailing stop level
               double potentialSL = currentPrice - (TrailingStopPips * pipValue);
               // Only move SL up, never down, and only if new level is higher than current SL
               if(potentialSL > currentStopLoss && (potentialSL - openPrice) > (TrailingStepPips * pipValue))
                 {
                  newStopLoss = potentialSL;
                 }
              }
            else if(positionType == POSITION_TYPE_SELL)
              {
               // Calculate new trailing stop level
               double potentialSL = currentPrice + (TrailingStopPips * pipValue);
               // Only move SL down, never up, and only if new level is lower than current SL
               if(potentialSL < currentStopLoss || currentStopLoss == 0)
                 {
                  if((openPrice - potentialSL) > (TrailingStepPips * pipValue) || currentStopLoss == 0)
                     newStopLoss = potentialSL;
                 }
              }

            // Modify stop loss if changed
            if(newStopLoss != currentStopLoss)
              {
               trade.PositionModify(PositionGetTicket(i), newStopLoss, PositionGetDouble(POSITION_TP));
               if(trade.ResultRetcode() == TRADE_RETCODE_DONE)
                  Print("Trailing stop updated for ticket ", PositionGetTicket(i), ". New SL: ", newStopLoss);
              }
           }
        }
     }  
     
}
//+------------------------------------------------------------------+